name: Build Docker Image

on:
  push:
    branches:
      - '**' # This will run the action on any branch push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Transform branch name
      id: prep
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_' | tr 'A-Z' 'a-z')"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ntmre:${{ steps.prep.outputs.branch }}
